"""Synchronous graphics-owner operations and bounded report handoff interfaces."""

from __future__ import annotations

from collections.abc import Callable
from concurrent.futures import Future
from typing import Protocol

from google.protobuf.message import Message

from cephvr.control.v1 import types_pb2 as pb
from cephvr.visual_stimulus.config.models.artifact_models import PreparedTrial
from cephvr.visual_stimulus.config.models.display_profile import DisplayProfile
from cephvr.visual_stimulus.rendering.types import (
    DiagnosticSnapshot,
    DisplayInitialization,
    OutputActivity,
    RenderUpdate,
    ResourceReleaseReport,
)
from cephvr.visual_stimulus.resources.calibration import PreparedCalibration
from cephvr.visual_stimulus.v1 import messages_pb2 as visual_stimulus
from cephvr.visual_stimulus.v1 import runtime_pb2 as vp


class EnginePort(Protocol):
    def service_display(self) -> bool: ...
    def poll_diagnostics(self) -> tuple[DiagnosticSnapshot, ...]: ...
    @property
    def diagnostics_pending(self) -> bool: ...
    def initialize_display(self, display: DisplayProfile) -> DisplayInitialization: ...
    def display_matches(self, display: DisplayProfile) -> bool: ...
    def prepare_trial(self, artifact: PreparedTrial) -> object: ...
    def begin_trial(self, trial_id: str, start_ns: int) -> None: ...
    def set_feedback_applier(self, applier: Callable[..., object] | None) -> None: ...
    def render_tick(
        self, now_ns: int, feedback_batch: tuple[object, ...] = ()
    ) -> RenderUpdate: ...
    def stop_trial(
        self, cutoff_ns: int | None = None
    ) -> tuple[OutputActivity, ...]: ...
    def cleanup(self) -> ResourceReleaseReport: ...


class PreparationPort(Protocol):
    def prepare_display(
        self,
        request: visual_stimulus.InitializeDisplay,
        announce: Callable[[str, str | None], None],
        deadline_ns: int,
    ) -> tuple[DisplayProfile, PreparedCalibration]: ...
    def initialize_display(
        self, display: DisplayProfile, calibration: PreparedCalibration
    ) -> DisplayInitialization: ...

    def prepare_graphics(self, artifacts: tuple[PreparedTrial, ...]) -> None: ...

    def prepare_trials(
        self,
        request: visual_stimulus.WorkerSetup,
        announce: Callable[[str, str | None], None],
        deadline_ns: int,
    ) -> tuple[PreparedTrial, ...]: ...
    def cleanup(self, deadline_ns: int) -> ResourceReleaseReport: ...


class FeedbackPort(Protocol):
    def configure(
        self,
        attachment: vp.FeedbackAttachment,
        artifacts: tuple[PreparedTrial, ...],
        announce: Callable[[str], None],
        deadline_ns: int,
        max_result_age_ns: int,
    ) -> None: ...
    def prepare_trial(self, artifact: PreparedTrial) -> Callable[..., object]: ...
    def begin_trial(self, trial_id: str) -> None: ...
    def capture_batch(self) -> tuple[object, ...]: ...
    def discard_pending(self) -> None: ...
    def close(self, deadline_ns: int) -> ResourceReleaseReport: ...


class RecordingPort(Protocol):
    def cleanup(self, deadline_ns: int) -> ResourceReleaseReport: ...

    def configure(
        self,
        request: visual_stimulus.WorkerSetup,
        announce: Callable[[str, str | None], None],
        deadline_ns: int,
    ) -> None: ...
    def prepare_artifacts(
        self, artifacts: tuple[PreparedTrial, ...], deadline_ns: int
    ) -> Future[None] | None: ...
    def schedule(
        self, request: visual_stimulus.WorkerSchedule, artifact: PreparedTrial
    ) -> Future[None] | None: ...
    def publication(self, report: visual_stimulus.WorkerRecipePublication) -> None: ...
    def before_render(self) -> None: ...
    def rendered(self, update: RenderUpdate) -> None: ...
    def diagnostics(self, records: tuple[DiagnosticSnapshot, ...]) -> None: ...
    def begin_finish(self, cutoff_ns: int, deadline_ns: int) -> None: ...
    def begin_cancel(self, deadline_ns: int) -> None: ...
    def poll_finished(self) -> tuple[pb.OutputResult, ...] | None: ...
    def review_summary(self) -> vp.ReviewRecordingSummary | None: ...


class ReportPort(Protocol):
    def send(self, method: str, message: Message, deadline_ns: int) -> None: ...
    def confirm(self, method: str, message: Message, deadline_ns: int) -> None: ...
