"""E14 strict Tracking file policies; no native or device imports."""

from __future__ import annotations

from pathlib import Path

from cephvr.shared.config import (
    ConfigurationError,
    LoadedPair,
    load_pair,
    policy_digest,
)

_POLICY_VERSION = 43
_POLICY_SHA256 = "fdf9ac7118b751703d01a322752a17a2d20a50a6248de9497e185fbb513ddc57"
_CONFIG_KEYS = frozenset(
    """
backend.enabled
estimator.fin_region.offset_degrees
estimator.fin_region.span_degrees
estimator.quality.maximum_native_cost
estimator.quality.maximum_normalized_residual
estimator.quality.minimum_neighbors
estimator.quality.noise_floor_px
estimator.quality.radius_cells
estimator.sections.count
estimator.smoothing.time_constant_s
estimator.support.minimum_accepted_area_fraction
flow.device_ordinal
flow.output_cost
flow.output_grid_px
flow.preset
flow.temporal_hints
frames.max_frame_age_ms
geometry.front_fraction
geometry.inner_clearance_fraction
geometry.outer_extent_fraction
geometry.squareness
geometry.taper
input.camera_role
limits.max_asset_bytes
limits.max_document_bytes
limits.max_native_bytes
limits.maximum_message_bytes
limits.movement_progress_timeout_s
limits.pose_progress_timeout_s
pipeline.name
pose.automatic_method
pose.contour.geometry_quality.minimum_axis_px
pose.contour.geometry_quality.minimum_base_width_px
pose.contour.geometry_quality.minimum_triangle_area_px2
pose.contour.maximum_area_px2
pose.contour.minimum_area_px2
pose.contour.minimum_axis_anisotropy
pose.history_capacity
pose.manual.image_height_px
pose.manual.image_width_px
pose.manual.landmarks.left_base.x_px
pose.manual.landmarks.left_base.y_px
pose.manual.landmarks.right_base.x_px
pose.manual.landmarks.right_base.y_px
pose.manual.landmarks.tip.x_px
pose.manual.landmarks.tip.y_px
pose.max_age_ms
pose.mode
pose.model.device_ordinal
pose.model.geometry_quality.minimum_axis_px
pose.model.geometry_quality.minimum_base_width_px
pose.model.geometry_quality.minimum_triangle_area_px2
pose.model.manifest.relative_path
pose.model.minimum_candidate_score
pose.model.minimum_landmark_score
pose.search_region.height_px
pose.search_region.width_px
pose.search_region.x_px
pose.search_region.y_px
pose.subject_reference.anterior.x_px
pose.subject_reference.anterior.y_px
pose.subject_reference.image_height_px
pose.subject_reference.image_width_px
pose.subject_reference.medial_left.x_px
pose.subject_reference.medial_left.y_px
pose.subject_reference.medial_right.x_px
pose.subject_reference.medial_right.y_px
pose.subject_reference.posterior.x_px
pose.subject_reference.posterior.y_px
pose.threshold.level
pose.threshold.polarity
recording.max_pending_bytes
recording.max_pending_records
recording.max_record_bytes
recording.save_tracking_data
recording.sync_interval_s
recording.write_progress_timeout_s
results.capacity_results
rpc.port
""".split()
)
_POLICY_KEYS = frozenset(
    """
estimator_input.pose_delivery
estimator_input.preaggregation
estimator_input.preprocessing_motion_compensation
estimator_input.samples
estimator_input.sample_position
estimator_input.sample_value
estimator_input.spatial_subsampling
execution.automatic_geometry_owner
execution.cpu_libraries
execution.estimator_device
execution.geometry_cache
execution.movement_delivery
execution.movement_worker
execution.preparation_device
execution.preview_handoff
execution.private_storage
execution.process_layout
extensions.method_commitment
extensions.registration
extensions.selection_scope
fin_flow.coverage
fin_flow.estimator_family
fin_flow.evidence
fin_flow.interpretation
fin_flow.quality_policy_ref
fin_flow.required_regions
fin_flow.response_policy_ref
fin_flow.sampling_geometry
fin_flow.sectioning
fin_flow.selection
fin_flow.smoothing_policy_ref
flow.adapter
flow.automatic_fallback
flow.input_buffers
flow.input_format
flow.input_mapping
flow.method
flow.output_representation
flow.readback
frames.bit_depth_policy
frames.camera_gap_action
frames.delay_action
frames.delay_measure
frames.delivery
frames.overflow_action
frames.pixel_processing
frames.representation
geometry.band_construction
geometry.band_distance_reference
geometry.clipping
geometry.distance_metric
geometry.distance_transform
geometry.geometry_libraries
geometry.implementation_id
geometry.implementation_version
geometry.outline_axes
geometry.rasterization
geometry.reference_shape
geometry.region_distance_units
geometry.region_layout
geometry.sampling_outline
geometry.sectioning_owner
geometry.settings_schema_id
input.selection_scope
input.source_scope
locomotion_output.channels
locomotion_output.camera_scale
locomotion_output.coordinate_frame
locomotion_output.meaning
locomotion_output.normalization
locomotion_output.positive_directions
locomotion_output.quantity
locomotion_output.translation_unit
locomotion_output.turning_unit
locomotion_output.unit_conversion
locomotion_output.visual_stimulus_control
locomotion_output.visual_stimulus_gain_owner
pipeline.composition
pipeline.implementation_version
pipeline.selection_scope
pipeline.supported_ids
pose.annotation_editing
pose.automatic_geometry_update
pose.automatic_mode_fallback
pose.automatic_scheduling
pose.candidate_selection
pose.history_reset_scope
pose.invalid_or_stale_action
pose.landmark_meanings
pose.landmarks
pose.manual_geometry
pose.pending_images
pose.search_area
pose.selection_scope
pose.subject_reference
pose.supported_automatic_methods
pose.supported_modes
pose.threshold_segmentation
pose_contour.axis_sign
pose_contour.boundary
pose_contour.clipped_component
pose_contour.components
pose_contour.implementation_version
pose_contour.landmarks
pose_contour.orientation
pose_contour.score
pose_contour.settings_schema_id
pose_model.adapter
pose_model.execution_provider
pose_model.export_scope
pose_model.format
pose_model.output_handoff
pose_model.preprocessing
pose_model.preprocessing_device
pose_model.runtime
recording.content
recording.crash_state
recording.durability
recording.file_suffix
recording.format
recording.recovery
recording.save_scope
recording.writer
results.credit_identity
results.delivery
results.overflow_action
results.reset_generation_order
results.reset_signal
sectioning.boundary_rule
sectioning.method
sectioning.numerics_revision
sectioning.origin
sectioning.outline_error_px
sectioning.perimeter_relative_error
sectioning.pixel_assignment
sectioning.reference_outline
sectioning.tie_rule
sectioning.traversal
water_flow.estimator_family
water_flow.evidence
water_flow.inference_target
water_flow.input_scope
water_flow.quality.boundary
water_flow.quality.combination
water_flow.quality.iteration
water_flow.quality.measured_buffer_mutation
water_flow.quality.method
water_flow.quality.minimum_support_failure
water_flow.quality.neighborhood
water_flow.quality.provider_cost
water_flow.quality.rejected_sample_action
water_flow.quality.residual
water_flow.response.translation
water_flow.response.translation_unit
water_flow.response.turning
water_flow.response.turning_reference
water_flow.response.turning_unit
water_flow.smoothing.initialization
water_flow.smoothing.invalid_or_gap_action
water_flow.smoothing.method
water_flow.smoothing.output
water_flow.support.coverage
water_flow.support.failure_action
water_flow.support.required_regions
""".split()
)


def load_files(root: Path) -> LoadedPair:
    policy_path = root / "contracts/policy/tracking_policy.toml"
    pair = load_pair(
        root / "config/backends/tracking_config.toml",
        policy_path,
        allowed_config_keys=_CONFIG_KEYS,
        allowed_policy_keys=_POLICY_KEYS,
    )
    if pair.policy_version != _POLICY_VERSION:
        raise ConfigurationError(f"Tracking policy_version must be {_POLICY_VERSION}")
    if policy_digest(pair.policy) != _POLICY_SHA256:
        raise ConfigurationError("Tracking policy differs from its implementation")
    return pair
