"""Visual Stimulus local preparation interfaces; no compiler/provider implementation."""
from typing import Protocol
from program_model import Program, TrialArenaBoundaries
from artifact_models import PreparedTrial
from display_profile import DisplayProfile
class PreparationBudget(Protocol):
    def check_cancelled_or_expired(self) -> None: ...
    def reserve(self, *, owner: str, cpu_bytes: int, gpu_bytes: int) -> None: ...
    def release(self, *, owner: str) -> None: ...
class ProgramCompiler(Protocol):
    def validate_pure(self, program: Program, boundaries: TrialArenaBoundaries) -> None: ...
    def prepare(self, program: Program, boundaries: TrialArenaBoundaries,
                display: DisplayProfile, seed_decimal: str,
                budget: PreparationBudget) -> PreparedTrial: ...
