"""E08 shared native mechanism interfaces; Windows runtime implementation exists.

See native-transport.md and reports/acquisition.md.
Backend messages, byte layouts, credits, overflow and
scheduling remain backend-owned. No universal queue/lifecycle framework.
"""
from dataclasses import dataclass
from typing import Literal, Protocol
@dataclass(frozen=True)
class ResourceKey:
    resource_id: str
    owner_process_instance_id: str # E08 process generation, not a reusable PID.
class BoundedMessagePipe(Protocol):
    def send_bytes(self, payload: bytes, *, deadline_ns: int) -> None: ...
    def recv_bytes(self, *, deadline_ns: int) -> bytes: ...
    def request_cancel(self) -> None: ...
    def close_after_io(self, *, deadline_ns: int) -> None:
        """Raise/report unconfirmed cleanup if native I/O is still using memory."""
        ...
class OwnedMapping(Protocol):
    @property
    def key(self) -> ResourceKey: ...
    @property
    def view(self) -> memoryview: ...
    def close_after_consumers(self, *, deadline_ns: int) -> None: ...
class ResourceLedger(Protocol):
    def register(self, key: ResourceKey, *, kind: str) -> None: ...
    def expect_attachment(self, key: ResourceKey, *, peer_instance_id: str,
                          transfer_id: str) -> None: ...
    def confirm_attachment(self, key: ResourceKey, *, peer_instance_id: str,
                           transfer_id: str) -> None: ...
    def confirm_release(self, key: ResourceKey, *, peer_instance_id: str,
                        transfer_id: str) -> None: ...
    def unresolved(self) -> tuple[ResourceKey, ...]: ...
class NativeTransport(Protocol):
    def create_mapping(self, key: ResourceKey, *, name: str, byte_length: int) -> OwnedMapping: ...
    def attach_mapping(self, key: ResourceKey, *, name: str, byte_length: int) -> OwnedMapping: ...
    def open_message_pipe(self, key: ResourceKey, *, name: str,
                          role: Literal['server','client'], expected_peer_instance_id: str,
                          startup_nonce: bytes, maximum_message_bytes: int,
                          deadline_ns: int) -> BoundedMessagePipe: ...
