"""Native ownership operations offered to control; no control-runtime references."""

from __future__ import annotations

from typing import Protocol

from cephvr.acquisition.v1.messages_pb2 import FrameBufferAttachment
from cephvr.tracking.config.models.methods import PreparedMethods
from cephvr.tracking.types import ImageLayout


class SessionPort(Protocol):
    @property
    def closed(self) -> bool: ...
    def prepare(self, frames: FrameBufferAttachment) -> PreparedMethods: ...
    @property
    def image_layout(self) -> ImageLayout: ...
    def begin(self) -> None: ...
    def run(self) -> None: ...
    def reconcile(self, deadline: int) -> bool: ...
    def close(self, deadline: int) -> bool: ...
    def progress_failure(self, now: int) -> str | None: ...


class FeedbackPort(Protocol):
    def prepare(self) -> None: ...
    @property
    def connected(self) -> bool: ...
    @property
    def failure(self) -> BaseException | None: ...
    def close(self, deadline: int) -> bool: ...
